language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r tests/requirements.txt

# command to run tests
script:
#  - pytest
  - pytest -v --cov=pxutil tests
