name: Create and Upload 200MB File

on:
    workflow_dispatch:

jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create 200MB file with random data
      run: dd if=/dev/urandom of=./200MB_file bs=1M count=200

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: 200MB_file
        path: ./200MB_file